# Generated by Django 2.0 on 2019-02-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typelink',
            name='link',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
