# Generated by Django 2.0 on 2019-02-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190301_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000, unique=True)),
                ('key', models.CharField(max_length=50)),
                ('sub_key', models.CharField(max_length=50)),
                ('pub', models.CharField(max_length=50)),
            ],
        ),
    ]
