# Generated by Django 2.0 on 2019-02-28 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_periodlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodlink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodlink',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
