# Generated by Django 2.0 on 2019-03-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20190301_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='periodlink',
            name='inventories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Inventory'),
        ),
        migrations.AddField(
            model_name='typelink',
            name='inventories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Inventory'),
        ),
    ]
