# Generated by Django 2.0 on 2019-03-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20190301_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inventories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Inventory')),
            ],
        ),
        migrations.RemoveField(
            model_name='typelink',
            name='inventories',
        ),
        migrations.AddField(
            model_name='typelink',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Product'),
        ),
    ]
