# Generated by Django 2.0 on 2019-03-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_schedulertracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulertracker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tasktracker',
            name='name',
        ),
    ]
