# Generated by Django 2.0 on 2019-03-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_auto_20190303_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulertracker',
            name='name',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
