# Generated by Django 2.0 on 2019-03-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_schedulertracker_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedulerTracker',
        ),
        migrations.DeleteModel(
            name='TaskTracker',
        ),
    ]
