# Generated by Django 2.0 on 2019-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_auto_20190303_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodlink',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='typelink',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
