# Generated by Django 2.0 on 2019-03-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_auto_20190303_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodlink',
            name='inventories',
        ),
        migrations.AddField(
            model_name='periodlink',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Product'),
        ),
    ]
