# Generated by Django 2.0 on 2019-03-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0014_auto_20190306_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000, unique=True)),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_key', models.CharField(blank=True, max_length=50, null=True)),
                ('pub', models.CharField(blank=True, max_length=50, null=True)),
                ('link_type', models.CharField(choices=[('insert', 'insert'), ('fetch', 'fetch')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='periodlink',
            name='products',
        ),
        migrations.RemoveField(
            model_name='typelink',
            name='products',
        ),
        migrations.RemoveField(
            model_name='typelink',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventories',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='links.Product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PeriodLink',
        ),
        migrations.DeleteModel(
            name='TypeLink',
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='links.Link'),
            preserve_default=False,
        ),
    ]
