# Generated by Django 2.0 on 2019-03-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0016_schedulerlookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
