# Generated by Django 2.0 on 2019-03-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0017_schedulertestrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulertestrecord',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
