# Generated by Django 2.0 on 2019-03-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0018_schedulertestrecord_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchedulerTestRecord',
            new_name='SchedulerRecord',
        ),
        migrations.AddField(
            model_name='link',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.SchedulerRecord'),
        ),
    ]
