# Generated by Django 2.0 on 2019-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0019_auto_20190322_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerrecord',
            name='number',
        ),
        migrations.AlterField(
            model_name='schedulerrecord',
            name='name',
            field=models.CharField(default='scheduler task', max_length=50),
            preserve_default=False,
        ),
    ]
