# Generated by Django 2.0 on 2019-03-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0021_auto_20190322_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerlookup',
            name='number',
        ),
        migrations.AlterField(
            model_name='schedulerlookup',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
