# Generated by Django 2.0 on 2019-03-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0024_auto_20190322_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(db_index=True, max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='identity',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
