# Generated by Django 2.0 on 2019-04-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0026_auto_20190326_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('insert', 'insert'), ('fetch', 'fetch'), ('commafeed', 'commafeed')], max_length=20),
        ),
    ]
